//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEDUschoolManaementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Exams = new HashSet<Exam>();
            this.Fees = new HashSet<Fee>();
            this.Students = new HashSet<Student>();
            this.StudentAttendances = new HashSet<StudentAttendance>();
            this.Subjects = new HashSet<Subject>();
            this.TeacherSubjects = new HashSet<TeacherSubject>();
        }
    
        public int classId { get; set; }
        public string className { get; set; }
    
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<TeacherSubject> TeacherSubjects { get; set; }
    }
}
