//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEDUschoolManaementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeesId { get; set; }
        public Nullable<int> classId { get; set; }
        public Nullable<int> FeesAmount { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
