//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEDUschoolManaementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Exams = new HashSet<Exam>();
            this.StudentAttendances = new HashSet<StudentAttendance>();
            this.TeacherSubjects = new HashSet<TeacherSubject>();
        }
    
        public int subjectId { get; set; }
        public Nullable<int> classId { get; set; }
        public string subjectName { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        public virtual ICollection<TeacherSubject> TeacherSubjects { get; set; }
    }
}
